# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_win64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_win64)
  Sandbox_config = debug_win64
  Air_Engine_config = debug_win64

else ifeq ($(config),debug_osx)
  Sandbox_config = debug_osx
  Air_Engine_config = debug_osx

else ifeq ($(config),debug_linux)
  Sandbox_config = debug_linux
  Air_Engine_config = debug_linux

else ifeq ($(config),release_win64)
  Sandbox_config = release_win64
  Air_Engine_config = release_win64

else ifeq ($(config),release_osx)
  Sandbox_config = release_osx
  Air_Engine_config = release_osx

else ifeq ($(config),release_linux)
  Sandbox_config = release_linux
  Air_Engine_config = release_linux

else ifeq ($(config),distribution_win64)
  Sandbox_config = distribution_win64
  Air_Engine_config = distribution_win64

else ifeq ($(config),distribution_osx)
  Sandbox_config = distribution_osx
  Air_Engine_config = distribution_osx

else ifeq ($(config),distribution_linux)
  Sandbox_config = distribution_linux
  Air_Engine_config = distribution_linux

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Sandbox Air-Engine

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Sandbox: Air-Engine
ifneq (,$(Sandbox_config))
	@echo "==== Building Sandbox ($(Sandbox_config)) ===="
	@${MAKE} --no-print-directory -C Sandbox -f Makefile config=$(Sandbox_config)
endif

Air-Engine:
ifneq (,$(Air_Engine_config))
	@echo "==== Building Air-Engine ($(Air_Engine_config)) ===="
	@${MAKE} --no-print-directory -C Air-Engine -f Makefile config=$(Air_Engine_config)
endif

clean:
	@${MAKE} --no-print-directory -C Sandbox -f Makefile clean
	@${MAKE} --no-print-directory -C Air-Engine -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_win64"
	@echo "  debug_osx"
	@echo "  debug_linux"
	@echo "  release_win64"
	@echo "  release_osx"
	@echo "  release_linux"
	@echo "  distribution_win64"
	@echo "  distribution_osx"
	@echo "  distribution_linux"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Sandbox"
	@echo "   Air-Engine"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"